#!/usr/bin/env node
/**
 * 泰语词库生成脚本
 * 读取 scripts/data/ 下的各词书数据，生成 src/data/vocabAllBooks.js
 *
 * 运行: node scripts/generateVocab.js
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, "data");
const OUTPUT = join(__dirname, "..", "src", "data", "vocabAllBooks.js");

/**
 * 紧凑格式每行:
 * ["泰文","读音","中文","词性","类别","难度","泰语例句","中文例句"]
 *
 * 脚本自动补充 id, book, review_status
 */
function parseBookFile(content, bookName) {
  const lines = content.split("\n").filter((l) => l.trim() && !l.trim().startsWith("//"));
  const entries = [];

  for (const line of lines) {
    try {
      const arr = JSON.parse(line.trim());
      if (!Array.isArray(arr) || arr.length < 6) continue;
      const [thai, pronunciation, chinese, pos, category, difficulty, exThai, exChinese] = arr;
      if (!thai || !chinese) continue;
      // Validate: Thai word must contain Thai script characters
      if (!/[\u0E00-\u0E7F]/.test(thai)) continue;
      entries.push({
        thai_word: thai,
        pronunciation: pronunciation || "",
        chinese_meaning: chinese,
        part_of_speech: pos || "",
        category: category || "",
        difficulty: difficulty || "beginner",
        example_thai: exThai || "",
        example_chinese: exChinese || "",
        book: bookName,
        review_status: "verified",
      });
    } catch {
      // skip malformed lines
    }
  }
  return entries;
}

function main() {
  mkdirSync(dirname(OUTPUT), { recursive: true });

  const files = readdirSync(DATA_DIR)
    .filter((f) => f.endsWith(".txt"))
    .sort();

  if (files.length === 0) {
    console.error("No .txt data files found in", DATA_DIR);
    process.exit(1);
  }

  let allEntries = [];
  const stats = [];

  for (const file of files) {
    const bookName = file.replace(".txt", "");
    const content = readFileSync(join(DATA_DIR, file), "utf-8");
    const entries = parseBookFile(content, bookName);
    entries.forEach((e, i) => {
      e.id = `gen-${bookName}-${String(i + 1).padStart(4, "0")}`;
    });
    allEntries = allEntries.concat(entries);
    stats.push({ book: bookName, count: entries.length });
  }

  // Deduplicate by thai_word, keep first occurrence
  const seen = new Set();
  const unique = [];
  for (const entry of allEntries) {
    const key = entry.thai_word;
    if (seen.has(key)) continue;
    seen.add(key);
    unique.push(entry);
  }

  const header = `// Auto-generated by scripts/generateVocab.js\n// Total: ${unique.length} entries from ${files.length} books\n// Do NOT edit manually — re-run: node scripts/generateVocab.js\n\nexport const vocabAllBooks = [\n`;
  const body = unique
    .map((e) => `  ${JSON.stringify(e)}`)
    .join(",\n");
  const footer = "\n];\n";

  writeFileSync(OUTPUT, header + body + footer, "utf-8");
  console.log(`\n✅ Generated ${OUTPUT}`);
  console.log(`   Books: ${files.length}`);
  console.log(`   Total entries: ${unique.length}`);
  for (const s of stats) {
    console.log(`   ${s.book}: ${s.count} words`);
  }
}

main();
